name: Test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  test:
    strategy:
      matrix:
        platform: [macos-11, macos-12]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Make test
      run: make test
