name: Test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  test:
    strategy:
      matrix:
        platform: [macos-12]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Unit Tests
      run: make test

    - name: End-to-End Tests
      run: make check

    - name: Install
      run: make install
      
    - name: Check Install
      run: make installcheck
